- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Install pacman packages
      community.general.pacman:
        name:
          - git
          - neovim
          - docker
          - docker-compose
          - docker-buildx
          - firefox
          - stow
          - tmux
          - rclone
          - ripgrep
          - npm
          - lazygit
          - yazi
          - sshfs
          - postgresql
          - prettier
          - yay
          - markdownlint-cli2
          - ast-grep
          - sqlfluff
          - luarocks
          - rust
          - composer
          - php
          - julia
          - python-pip
          - tree
          - tail-tray
          - tailscale
          - torbrowser-launcher
          - telegram-desktop
        state: present
